<?php

include "rsc_cite.blocks.inc";


/**
 * Implements hook_permission().
 */
function rsc_cite_permission() {
  return array(
    'administer rsc_cite' => array(
      'title' => t('Administer RSC Cite'),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function rsc_cite_menu() {
  $items = array();

  $items['admin/structure/rsc_cite'] = array(
    'title' => t('RSC Cite'),
    'description' => t('Configure RSC Cite.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rsc_cite_settings'),
    'file' => 'rsc_cite.admin.inc',
    'access arguments' => array('administer rsc_cite'),
  );

  return $items;
}


/**
 * Implements hook_node_info().
 * 
 * Defines the content types used by rsc_cite
 */
function rsc_cite_node_info() {
  return array(
    'rsc_cite_short' => array(
      'name'        => t('RSC Cite: Short citation'),
      'base'        => 'rsc_cite_short',
      'description' => t("A short citation, with an author."),
      'locked'      => TRUE,  // admin cannot change machine name
      'has_title'   => FALSE, // no title field
    ),
    'rsc_cite_paragraph' => array(
      'name'        => t('RSC Cite: Paragraph citation'),
      'base'        => 'rsc_cite_paragraph',
      'description' => t("A citation of any length, with an author and optional tags."),
      'locked'      => TRUE,  // admin cannot change machine name
    ),
  );
}


/**
 * Implements hook_form().
 * 
 * These forms allow the content types to be edited
 */
function rsc_cite_short_form($node, &$form_state) {
  return node_content_form($node, $form_state);
}
function rsc_cite_paragraph_form($node, &$form_state) {
  return node_content_form($node, $form_state);
}

